### ISSUE TITLE
gunit: error message for invalid tags is confusing

### ISSUE THREAD

**Issue by viktornordling** [palantir/godel#133]
If you run `./godelw test --tags=bla` you get a message saying `invalid tags: "integration"`. This is completely reasonable once you know how the configuration of tags works. 

However, since `go test -tags=bla` will work (if you add `// +build bla` at the top of a test file), this is pretty confusing. Could we consider making the error message more clear, for example by saying something like `tag "bla" not found in test.yml` or `see the documentation for how to add tags in godel at https://github.com/palantir/godel/wiki/Configuration#testyml`.

**Comment by nmiyake** [comment]
In your example, the output would be `invalid tags: "bla"`, right?

Agree that output could be a bit more helpful. However, it won't be able to reference the configuration file because it doesn't know about the location of configuration at runtime (the command uses the config piped into it). Broader point is valid, though, and will think about it.

**Comment by viktornordling** [comment]
Yeah, I did mean `invalid tags: "bla"`, sorry.
