### ISSUE TITLE
Consider running checks in parallel

### ISSUE THREAD

**Issue by viktornordling** [palantir/godel#148]
Running `./godelw check` takes about 30 seconds for the project I currently work on (5k loc excluding vendored libraries), which is enough of a delay to break my flow. Would it be possible to run at least some of these checks in parallel? 

I understand that the mutating checks can't really be run in parallel, but the ones that don't mutate code should probably be parallelizable?

**Comment by nmiyake** [comment]
The initial thinking was that I wanted this to execute sequentially so that the output and failure results would be deterministic, but agree that this could significantly improve runtime in certain scenarios and would probably be worth it (and we can always introduce it as flagged behavior or provide a flag that turns the behavior off).

**Comment by viktornordling** [comment]
Yeah, makes sense re the output, you'd have to do something clever with that (either colorize like docker-compose does or somehow collect the logs and show them once things are done).

**Comment by nmiyake** [comment]
Yeah I don't really want to interleave the output (even if you color-code, makes it much harder to copy/paste or figure out what's going on).

That reminds me a bit more of another trade-off here. Right now, the code basically passes the `os.Stdout` of gödel directly to the subcheck so that output can be streamed directly from the check to the output stream (so you can get partial progress rather than just waiting for the check to complete and then dumping all the output at once).

The easiest parallel implementation I can think of would all involve buffering the output of the parallel checks in-memory and then dumping out to `stdout` once we're ready for the check output. I think this should work, but would change the interaction/experience.

**Comment by viktornordling** [comment]
Yep, I hear you. If we'd do this, I can see how it would be behind a flag only, so feel free to close this issue.

**Comment by nmiyake** [comment]
I think the issue it totally legitimate and would provide real value, so keeping it open -- definitely worth at least exploring. Just flagging that it won't necessarily be an easy fix and documenting some of the things to consider when tackling a solution for this.

**Comment by dreamlibrarian** [comment]
https://github.com/alecthomas/gometalinter seems to be solving the same general set of issues as our current check build (less the JUnit formatting AFAICT?); possibly an opportunity for integrating a third party tool to lower maintenance load?

**Comment by jdhenke** [comment]
@dreamlibrarian now not sure if you meant it this way, but I looked to see if `gometalinter` used or exposed a package to consolidate checks run in parallel, and it appears that the logic is baked into the `main` package sadly, but for reference, the approach they took was to:

* [execute each linter in parallel](https://github.com/alecthomas/gometalinter/blob/master/execute.go#L121)
* each `Command` [writes to a buffer](https://github.com/alecthomas/gometalinter/blob/master/execute.go#L150-L152)
* [the _entirety_ of each output is matched against a regex](https://github.com/alecthomas/gometalinter/blob/master/execute.go#L206) to find all issues
* each match results in an `Issue` [sent to a shared channel of all incoming `Issue`s](https://github.com/alecthomas/gometalinter/blob/master/execute.go#L274)
* that channel is then read and [possibly aggregated/sorted](https://github.com/alecthomas/gometalinter/blob/master/execute.go#L77-L78)
* this yields a final channel to [range over to print all issues](https://github.com/alecthomas/gometalinter/blob/master/main.go#L274-L280)

And it looks like it supports [checkstyle output](https://github.com/alecthomas/gometalinter/blob/master/checkstyle.go#L29-L65), which seems like a reasonable choice, no?

**Comment by nmiyake** [comment]
Fixed in the latest version of the test plugin used in gödel 2.0.

The new behavior runs each separate check in a separate channel, processes the output of the check and generates issues based on them.

**Comment by nmiyake** [comment]
See https://github.com/palantir/godel/wiki/Check#run-checks for example of new output.

Parallelization can also be disabled using the `--parallel=false` flag: https://github.com/palantir/godel/wiki/Check#run-checks-sequentially
