### ISSUE TITLE
X-Checksum-SHA256 header breaks uploads to Artifactory 5.5+

### ISSUE THREAD

**Issue by bmoylan** [palantir/godel#229]

**Comment by nmiyake** [comment]
After doing more investigation locally, we have determined that this is actually working as expected/intended, but there is an edge case/bug in Artifactory itself.

It appears that, if an artifact was previously uploaded and it somehow set its SHA-256 value to be `null`, then uploading an artifact with the same checksum at a later time that provides a SHA-256 value can fail. This seems like it is an Artifactory-side bug that can hopefully be fixed by them (or by re-creating the artifact indices).

In the meantime, if one encounters this, the suggested workaround is to make some kind of change/modification to ensure that the generated artifacts have a new checksum (in this case, the publish should succeed).
