### ISSUE TITLE
distgo: docker image distribution

### ISSUE THREAD

**Issue by bmoylan** [palantir/godel#43]
A la https://github.com/palantir/gradle-docker

**Comment by bmoylan** [comment]
I'm doing things with shell scripts and it feels barbaric, I may take a stab at this today.

**Comment by andybradshaw** [comment]
I've started working on this. Should hopefully have a PR soon.

**Comment by nmiyake** [comment]
Great! Feel free to let me know if you have any questions about where the code is, how to wire up tests, etc. (otherwise will just comment on the PR). Thanks!

**Comment by nmiyake** [comment]
Chatted with @yvdinesh about this on Friday and outlined a tentative plan for this. Recording here for posterity. At the highest level, we will want to handle building Docker images and publishing those images. We only talked about the former (although the latter should be fairly easy to do as a `publish` task), so recording those thoughts here.

The essential task that we want to do is to invoke `docker build` in some directory specified by configuration. The specified directory is assumed to have a pre-existing `Dockerfile` in the directory that has been manually specified/set up. It should also contain any static resources that are required as part of the build.

The configuration for the `docker` dist type should specify the following:
* Directory in which `docker build` should be executed
* The `dist` outputs that are required for the Docker build task (`product`, `dist-type` pairs)
* Any dependencies on other `docker build` dist outputs
  * Dependencies must be a DAG -- no cycles
* Optionally, an arbitrary bash script that can be run
  * Script is run after all dependent dist tasks are run, but before `docker build` is run

On execution, we do the following:

* Determine set of distributions that need to be built
  * Based on `dist` dependencies in configuration for this task and all dependent Docker tasks
* Run `dist` task for all of those dependencies
* If there are dependent Docker builds, run them
  * Need mechanism to properly order the DAG based on dependency order
* Run the user-provided script
  * Generated dist artifacts and Docker images should be available as environment variables
* Run the `docker build` task in the build directory
* Run `docker tag` to tag the image that was built

We're pretty sure that this should cover most scenarios. As currently constructed, we don't automatically move or copy the `dist` outputs that are created. This will mean that almost every Docker task will need to define a custom script action that either moves or copies the dist output. If the overhead for this seems onerous, we could automate this as part of the task, but not sure what assumptions we can make about moving or copying the dists (which could be large), which is why I have a slight preference for letting the user specify it.

@yvdinesh said that he was going to take a stab at this based on the approach outlined above. If people have any thoughts/concerns/input, please chime in!

**Comment by nmiyake** [comment]
Fixed by #104
