### ISSUE TITLE
go get -u github.com/palantir/godel/godelinit fails on archive dependency

### ISSUE THREAD

**Issue by andysworkshop** [palantir/godel#462]
Fresh install on Windows/cygwin:
```
$ go get -u github.com/palantir/godel/godelinit
go: finding github.com/palantir/godel/godelinit latest
# github.com/palantir/godel/framework/builtintasks/installupdate
..\..\..\go\pkg\mod\github.com\palantir\godel@v2.16.0+incompatible\framework\builtintasks\installupdate\install.go:68:26: invalid method expression archiver.TarGz.Open (needs pointer receiver: (*archiver.TarGz).Open)
```
Fixed by locally changing the offending line 68 to:
```
if err := archiver.DefaultTarGz.Unarchive(tgzFilePath, tmpDir); err != nil {
```
I'd submit a PR but that's not allowed by company policy. Sorry.

[edit] OK so I now see that godel isn't compatible with Windows at all so I've had to drop it from the project. This error doesn't look platform-specific though so you may still be interested in fixing it.

**Comment by uded** [comment]
I am running everything on a Mac and have the same issue I believe:

```
go: finding github.com/palantir/godel/godelinit latest
# github.com/palantir/godel/framework/builtintasks/installupdate
../../../../go/pkg/mod/github.com/palantir/godel@v2.16.0+incompatible/framework/builtintasks/installupdate/install.go:68:26: invalid method expression archiver.TarGz.Open (needs pointer receiver: (*archiver.TarGz).Open)
```

Version: `go version go1.12.7 darwin/amd64`

**Comment by tomqwpl** [comment]
Ah. Shame it's not compatible with Windows.

**Comment by tomqwpl** [comment]
I seem to get this running under Ubuntu within WSL2 on Windows, so, as I understand it, a standard linux distro.

    go version go1.13.8 linux/amd64

    go get github.com/palantir/godel/godelinit
    # github.com/palantir/godel/framework/builtintasks/installupdate

/home/tomq/go/pkg/mod/github.com/palantir/godel@v2.20.0+incompatible/framework/builtintasks/installupdate/install.go:68:26:` invalid method expression archiver.TarGz.Open (needs pointer receiver: (*archiver.TarGz).Open)

**Comment by tomqwpl** [comment]
Changing as per andysworkshop comment makes it work, but on the fact of it, `go get github.com/palantir/godel/godelinit` doesn't appear to work otherwise.

**Comment by nmiyake** [comment]
Sorry for the late response -- since godel is on major version 2, the module path one would need to use for `go get` would be `go get github.com/palantir/godel/v2/godelinit` (the comments above are missing the "v2" part of the path).

However, now that Go 1.16 supports version suffixes in the "install" command (https://golang.org/doc/go1.16#go-command), `go install github.com/palantir/godel/v2/godelinit@latest` should be the canonical way to ensure that the latest version of `godelinit` is installed locally (this will not modify any entries in the `go.mod` file). The documentation has also been updated to reflect this: https://github.com/palantir/godel/tree/master/godelinit#installation

Closing out since this should be resolved.
